### ISSUE TITLE
Installing pyprob using pip gets an older version

### ISSUE THREAD

**Issue by saeidnp** [probprog/pyprob#11]
I tried installing pyprob using `pip install pyprob`, but for running the examples afterwards it complains `cannot import name 'Model'`
It turns out that the installed pyprob version was 0.10.0.dev2 as using `pydoc.help` on the package says:
```
Help on package pyprob:

NAME
    pyprob

PACKAGE CONTENTS
    comm
    console (package)
    distributions
    inference
    logger
    nn
    pool
    state
    trace
    util
    zmq

VERSION
    0.10.0.dev2

FILE
    /Users/saeidnaderi/anaconda3/lib/python3.6/site-packages/pyprob/__init__.py
```

**Comment by gbaydin** [comment]
The package on PyPI has been updated to the latest version. We will integrate PyPI distribution uploads with CI workflow.
