### ISSUE TITLE
Separate Priors and Proposals in the Protocol

### ISSUE THREAD

**Issue by Lezcano** [probprog/pyprob#3]
Proposal distributions should not be forced upon the client by default in the protocol.

Separating the priors and the proposals would mean that the client could try to use different families of proposals for different priors in her model and then compare the performance.

An example of the new protocol would include a `Sample` message with a format similar to:
```
table Sample {
    time:int;
    address:string;
    instance:int;
    prior:Distribution;
    proposal:Distribution;
    value:NDArray;
}
```
and `Distributions` with just the parameters of the distribution itself like
```
table Normal {
    mean:double;
    std:double;
}
```

**Comment by gbaydin** [comment]
These are no longer a part of the protocol and therefore I'm closing this issue.
